/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.GameController;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import static javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED;
import javax.swing.border.LineBorder;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author Jeffrey Leiva
 */
public class GameView extends javax.swing.JFrame {

    /**
     * Creates new form GameView
     */
    private static final int NUM_ROWS = 13;
    private static final int NUM_COLS = 4;
    public JButton [][] cardButtons = new JButton[NUM_ROWS][NUM_COLS];
    
    
    int xMouse, yMouse;
    GameController controller;
    public GameView() {
        initComponents();
        initCardBoard();
        this.setPreferredSize(new Dimension(820,600));
    }
    
    
    public void setController(GameController controller){
        this.controller = controller;
    }
    
    public JButton[][] getButtons(){
        return this.cardButtons;
    }
    
    public void updateScore(int score) {
       this.score.setText(""+score+"");
    }

    private void initCardBoard(){
        int columnSpacing = 40;
        int rowSpacing = 40;
        int buttonWidth = 100;
        int buttonHeight = 100;
        JPanel bgPanel = new JPanel();
        bgPanel.setLayout(new AbsoluteLayout());
        bgPanel.setBackground(new Color(87,89,94));
        for(int i = 0; i < NUM_ROWS; i++){
            for(int j = 0; j < NUM_COLS; j++){
                   cardButtons[i][j] = new JButton();
                   bgPanel.add(cardButtons[i][j], new AbsoluteConstraints(j*buttonWidth+columnSpacing,i*buttonHeight+rowSpacing, buttonWidth, buttonHeight));
                   cardButtons[i][j].setBorder(null);
            }
        }
        
        JScrollPane scrollPane = new JScrollPane();
        scrollPane.setViewportView(bgPanel);
        scrollPane.setVerticalScrollBar(new ScrollBarCustom());
        frameBgPanel.add(scrollPane, new AbsoluteConstraints(0,50,500,540));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameBgPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JPanel();
        closePanel = new javax.swing.JPanel();
        exitLabel = new javax.swing.JLabel();
        MinimizePanel = new javax.swing.JPanel();
        minimizeLabel = new javax.swing.JLabel();
        scorePanelSign = new javax.swing.JPanel();
        scoreLabelSign = new javax.swing.JLabel();
        scorePanel = new javax.swing.JPanel();
        score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        frameBgPanel.setBackground(new java.awt.Color(27, 28, 31));
        frameBgPanel.setPreferredSize(new java.awt.Dimension(820, 590));
        frameBgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuBar.setBackground(new java.awt.Color(255, 255, 255));
        menuBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                menuBarMouseDragged(evt);
            }
        });
        menuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuBarMousePressed(evt);
            }
        });

        closePanel.setBackground(new java.awt.Color(255, 255, 255));

        exitLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel.setText("X");
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout closePanelLayout = new javax.swing.GroupLayout(closePanel);
        closePanel.setLayout(closePanelLayout);
        closePanelLayout.setHorizontalGroup(
            closePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        closePanelLayout.setVerticalGroup(
            closePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        MinimizePanel.setBackground(new java.awt.Color(255, 255, 255));

        minimizeLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        minimizeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeLabel.setText("-");
        minimizeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MinimizePanelLayout = new javax.swing.GroupLayout(MinimizePanel);
        MinimizePanel.setLayout(MinimizePanelLayout);
        MinimizePanelLayout.setHorizontalGroup(
            MinimizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minimizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        MinimizePanelLayout.setVerticalGroup(
            MinimizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minimizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBarLayout.createSequentialGroup()
                .addGap(0, 674, Short.MAX_VALUE)
                .addComponent(MinimizePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(closePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MinimizePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        frameBgPanel.add(menuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 50));

        scorePanelSign.setBackground(new java.awt.Color(87, 89, 94));

        scoreLabelSign.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        scoreLabelSign.setForeground(new java.awt.Color(255, 255, 255));
        scoreLabelSign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabelSign.setText("Puntuación");

        javax.swing.GroupLayout scorePanelSignLayout = new javax.swing.GroupLayout(scorePanelSign);
        scorePanelSign.setLayout(scorePanelSignLayout);
        scorePanelSignLayout.setHorizontalGroup(
            scorePanelSignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scoreLabelSign, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        scorePanelSignLayout.setVerticalGroup(
            scorePanelSignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scorePanelSignLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(scoreLabelSign, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        frameBgPanel.add(scorePanelSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 320, 70));

        scorePanel.setBackground(new java.awt.Color(87, 89, 94));

        score.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        score.setForeground(new java.awt.Color(255, 255, 255));
        score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout scorePanelLayout = new javax.swing.GroupLayout(scorePanel);
        scorePanel.setLayout(scorePanelLayout);
        scorePanelLayout.setHorizontalGroup(
            scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(score, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        scorePanelLayout.setVerticalGroup(
            scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(score, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        frameBgPanel.add(scorePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, -1, -1));

        getContentPane().add(frameBgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarMouseDragged
        // TODO add your handling code here:
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
       this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_menuBarMouseDragged

    private void menuBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_menuBarMousePressed

    private void exitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseEntered
        // TODO add your handling code here:
         closePanel.setBackground(Color.red);
         exitLabel.setForeground(Color.white);
    }//GEN-LAST:event_exitLabelMouseEntered

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseExited
        // TODO add your handling code here:
         closePanel.setBackground(new Color(255,255,255));
         exitLabel.setForeground(new Color(187,187,187));
    }//GEN-LAST:event_exitLabelMouseExited

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void minimizeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseEntered
        // TODO add your handling code here:
        MinimizePanel.setBackground(new Color(0, 60, 255));
        minimizeLabel.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_minimizeLabelMouseEntered

    private void minimizeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseExited
        // TODO add your handling code here:
        MinimizePanel.setBackground(new Color(255,255,255));
        minimizeLabel.setForeground(new Color(187,187,187));
    }//GEN-LAST:event_minimizeLabelMouseExited

    private void minimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseClicked
        // TODO add your handling code here:
                this.setExtendedState(GameView.ICONIFIED);
    }//GEN-LAST:event_minimizeLabelMouseClicked

    public void showMessageDidNotMatch(){
         JOptionPane.showMessageDialog(frameBgPanel, "La pareja no es correcta");
    }
    
    public void showMessageWin(){
        JOptionPane.showMessageDialog(frameBgPanel, "Has ganado");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MinimizePanel;
    private javax.swing.JPanel closePanel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JPanel frameBgPanel;
    private javax.swing.JPanel menuBar;
    private javax.swing.JLabel minimizeLabel;
    private javax.swing.JLabel score;
    private javax.swing.JLabel scoreLabelSign;
    private javax.swing.JPanel scorePanel;
    private javax.swing.JPanel scorePanelSign;
    // End of variables declaration//GEN-END:variables


}
